export const Cources = {
    Data:[
        {
            Name:"DAC",
            instituteName:"c-DAC",
             contact:"69699696",
            City:"PUNE",
            Image:"image3.webp",
        },
        {
            Name:"Networking",
            instituteName:"Seed Infotech",
            contact:"9696969699",
            City:"PUNE",
            Image:"image3.webp",
        },
        {
            Name:"B.E.(CS)",
            instituteName:"MIT",
            contact:"858858858",
            City:"PUNE",
            Image:"image3.webp",
        },
        {
            Name:"REACT",
            instituteName:"P-DAC",
            contact:"4545454",
            City:"PUNE",
            Image:"image3.webp",
        },
        {
            Name:"REDUX",
            instituteName:"P_DAC",
            contact:"15215",
            City:"PUNE",
            Image:"image3.webp",
        },
        {
            Name:"Bootstrap",
            instituteName:"P_DAC",
            contact:"9545969",
            City:"PUNE",
            Image:"image3.webp",
        },
    ]
}